/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './pages/__root';
import { Route as legacyRouteRouteImport } from './pages/(legacy)/route';
import { Route as experimentalRouteRouteImport } from './pages/(experimental)/route';
import { Route as IndexRouteImport } from './pages/index';
import { Route as legacySettingsRouteImport } from './pages/(legacy)/settings';
import { Route as legacyRulesRouteImport } from './pages/(legacy)/rules';
import { Route as legacyProxiesRouteImport } from './pages/(legacy)/proxies';
import { Route as legacyProvidersRouteImport } from './pages/(legacy)/providers';
import { Route as legacyProfilesRouteImport } from './pages/(legacy)/profiles';
import { Route as legacyLogsRouteImport } from './pages/(legacy)/logs';
import { Route as legacyDashboardRouteImport } from './pages/(legacy)/dashboard';
import { Route as legacyConnectionsRouteImport } from './pages/(legacy)/connections';
import { Route as legacyBrowserRouteImport } from './pages/(legacy)/browser';
import { Route as experimentalExperimentalSettingsRouteRouteImport } from './pages/(experimental)/experimental/settings/route';
import { Route as experimentalExperimentalRulesRouteRouteImport } from './pages/(experimental)/experimental/rules/route';
import { Route as experimentalExperimentalProxiesRouteRouteImport } from './pages/(experimental)/experimental/proxies/route';
import { Route as experimentalExperimentalProvidersRouteRouteImport } from './pages/(experimental)/experimental/providers/route';
import { Route as experimentalExperimentalProfilesRouteRouteImport } from './pages/(experimental)/experimental/profiles/route';
import { Route as experimentalExperimentalLogsRouteRouteImport } from './pages/(experimental)/experimental/logs/route';
import { Route as experimentalExperimentalDashboardRouteRouteImport } from './pages/(experimental)/experimental/dashboard/route';
import { Route as experimentalExperimentalConnectionsRouteRouteImport } from './pages/(experimental)/experimental/connections/route';
import { Route as experimentalExperimentalSettingsIndexRouteImport } from './pages/(experimental)/experimental/settings/index';
import { Route as experimentalExperimentalProxiesIndexRouteImport } from './pages/(experimental)/experimental/proxies/index';
import { Route as experimentalExperimentalSettingsWebUiRouteRouteImport } from './pages/(experimental)/experimental/settings/web-ui/route';
import { Route as experimentalExperimentalSettingsUserInterfaceRouteRouteImport } from './pages/(experimental)/experimental/settings/user-interface/route';
import { Route as experimentalExperimentalSettingsSystemServiceRouteRouteImport } from './pages/(experimental)/experimental/settings/system-service/route';
import { Route as experimentalExperimentalSettingsSystemProxyRouteRouteImport } from './pages/(experimental)/experimental/settings/system-proxy/route';
import { Route as experimentalExperimentalSettingsSystemBehaviorRouteRouteImport } from './pages/(experimental)/experimental/settings/system-behavior/route';
import { Route as experimentalExperimentalSettingsNyanpasuConfigRouteRouteImport } from './pages/(experimental)/experimental/settings/nyanpasu-config/route';
import { Route as experimentalExperimentalSettingsDebugUtilsRouteRouteImport } from './pages/(experimental)/experimental/settings/debug-utils/route';
import { Route as experimentalExperimentalSettingsClashSettingsRouteRouteImport } from './pages/(experimental)/experimental/settings/clash-settings/route';
import { Route as experimentalExperimentalSettingsClashFiledRouteRouteImport } from './pages/(experimental)/experimental/settings/clash-filed/route';
import { Route as experimentalExperimentalSettingsClashExternalControllRouteRouteImport } from './pages/(experimental)/experimental/settings/clash-external-controll/route';
import { Route as experimentalExperimentalSettingsClashCoreRouteRouteImport } from './pages/(experimental)/experimental/settings/clash-core/route';
import { Route as experimentalExperimentalSettingsAboutRouteRouteImport } from './pages/(experimental)/experimental/settings/about/route';
import { Route as experimentalExperimentalProxiesGroupNameRouteImport } from './pages/(experimental)/experimental/proxies/group/$name';
const legacyRouteRoute = legacyRouteRouteImport.update({
    id: '/(legacy)',
    getParentRoute: () => rootRouteImport,
});
const experimentalRouteRoute = experimentalRouteRouteImport.update({
    id: '/(experimental)',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const legacySettingsRoute = legacySettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => legacyRouteRoute,
});
const legacyRulesRoute = legacyRulesRouteImport.update({
    id: '/rules',
    path: '/rules',
    getParentRoute: () => legacyRouteRoute,
});
const legacyProxiesRoute = legacyProxiesRouteImport.update({
    id: '/proxies',
    path: '/proxies',
    getParentRoute: () => legacyRouteRoute,
});
const legacyProvidersRoute = legacyProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => legacyRouteRoute,
});
const legacyProfilesRoute = legacyProfilesRouteImport.update({
    id: '/profiles',
    path: '/profiles',
    getParentRoute: () => legacyRouteRoute,
});
const legacyLogsRoute = legacyLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => legacyRouteRoute,
});
const legacyDashboardRoute = legacyDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => legacyRouteRoute,
});
const legacyConnectionsRoute = legacyConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => legacyRouteRoute,
});
const legacyBrowserRoute = legacyBrowserRouteImport.update({
    id: '/browser',
    path: '/browser',
    getParentRoute: () => legacyRouteRoute,
});
const experimentalExperimentalSettingsRouteRoute = experimentalExperimentalSettingsRouteRouteImport.update({
    id: '/experimental/settings',
    path: '/experimental/settings',
    getParentRoute: () => experimentalRouteRoute,
});
const experimentalExperimentalRulesRouteRoute = experimentalExperimentalRulesRouteRouteImport.update({
    id: '/experimental/rules',
    path: '/experimental/rules',
    getParentRoute: () => experimentalRouteRoute,
});
const experimentalExperimentalProxiesRouteRoute = experimentalExperimentalProxiesRouteRouteImport.update({
    id: '/experimental/proxies',
    path: '/experimental/proxies',
    getParentRoute: () => experimentalRouteRoute,
});
const experimentalExperimentalProvidersRouteRoute = experimentalExperimentalProvidersRouteRouteImport.update({
    id: '/experimental/providers',
    path: '/experimental/providers',
    getParentRoute: () => experimentalRouteRoute,
});
const experimentalExperimentalProfilesRouteRoute = experimentalExperimentalProfilesRouteRouteImport.update({
    id: '/experimental/profiles',
    path: '/experimental/profiles',
    getParentRoute: () => experimentalRouteRoute,
});
const experimentalExperimentalLogsRouteRoute = experimentalExperimentalLogsRouteRouteImport.update({
    id: '/experimental/logs',
    path: '/experimental/logs',
    getParentRoute: () => experimentalRouteRoute,
});
const experimentalExperimentalDashboardRouteRoute = experimentalExperimentalDashboardRouteRouteImport.update({
    id: '/experimental/dashboard',
    path: '/experimental/dashboard',
    getParentRoute: () => experimentalRouteRoute,
});
const experimentalExperimentalConnectionsRouteRoute = experimentalExperimentalConnectionsRouteRouteImport.update({
    id: '/experimental/connections',
    path: '/experimental/connections',
    getParentRoute: () => experimentalRouteRoute,
});
const experimentalExperimentalSettingsIndexRoute = experimentalExperimentalSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => experimentalExperimentalSettingsRouteRoute,
});
const experimentalExperimentalProxiesIndexRoute = experimentalExperimentalProxiesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => experimentalExperimentalProxiesRouteRoute,
});
const experimentalExperimentalSettingsWebUiRouteRoute = experimentalExperimentalSettingsWebUiRouteRouteImport.update({
    id: '/web-ui',
    path: '/web-ui',
    getParentRoute: () => experimentalExperimentalSettingsRouteRoute,
});
const experimentalExperimentalSettingsUserInterfaceRouteRoute = experimentalExperimentalSettingsUserInterfaceRouteRouteImport.update({
    id: '/user-interface',
    path: '/user-interface',
    getParentRoute: () => experimentalExperimentalSettingsRouteRoute,
});
const experimentalExperimentalSettingsSystemServiceRouteRoute = experimentalExperimentalSettingsSystemServiceRouteRouteImport.update({
    id: '/system-service',
    path: '/system-service',
    getParentRoute: () => experimentalExperimentalSettingsRouteRoute,
});
const experimentalExperimentalSettingsSystemProxyRouteRoute = experimentalExperimentalSettingsSystemProxyRouteRouteImport.update({
    id: '/system-proxy',
    path: '/system-proxy',
    getParentRoute: () => experimentalExperimentalSettingsRouteRoute,
});
const experimentalExperimentalSettingsSystemBehaviorRouteRoute = experimentalExperimentalSettingsSystemBehaviorRouteRouteImport.update({
    id: '/system-behavior',
    path: '/system-behavior',
    getParentRoute: () => experimentalExperimentalSettingsRouteRoute,
});
const experimentalExperimentalSettingsNyanpasuConfigRouteRoute = experimentalExperimentalSettingsNyanpasuConfigRouteRouteImport.update({
    id: '/nyanpasu-config',
    path: '/nyanpasu-config',
    getParentRoute: () => experimentalExperimentalSettingsRouteRoute,
});
const experimentalExperimentalSettingsDebugUtilsRouteRoute = experimentalExperimentalSettingsDebugUtilsRouteRouteImport.update({
    id: '/debug-utils',
    path: '/debug-utils',
    getParentRoute: () => experimentalExperimentalSettingsRouteRoute,
});
const experimentalExperimentalSettingsClashSettingsRouteRoute = experimentalExperimentalSettingsClashSettingsRouteRouteImport.update({
    id: '/clash-settings',
    path: '/clash-settings',
    getParentRoute: () => experimentalExperimentalSettingsRouteRoute,
});
const experimentalExperimentalSettingsClashFiledRouteRoute = experimentalExperimentalSettingsClashFiledRouteRouteImport.update({
    id: '/clash-filed',
    path: '/clash-filed',
    getParentRoute: () => experimentalExperimentalSettingsRouteRoute,
});
const experimentalExperimentalSettingsClashExternalControllRouteRoute = experimentalExperimentalSettingsClashExternalControllRouteRouteImport.update({
    id: '/clash-external-controll',
    path: '/clash-external-controll',
    getParentRoute: () => experimentalExperimentalSettingsRouteRoute,
});
const experimentalExperimentalSettingsClashCoreRouteRoute = experimentalExperimentalSettingsClashCoreRouteRouteImport.update({
    id: '/clash-core',
    path: '/clash-core',
    getParentRoute: () => experimentalExperimentalSettingsRouteRoute,
});
const experimentalExperimentalSettingsAboutRouteRoute = experimentalExperimentalSettingsAboutRouteRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => experimentalExperimentalSettingsRouteRoute,
});
const experimentalExperimentalProxiesGroupNameRoute = experimentalExperimentalProxiesGroupNameRouteImport.update({
    id: '/group/$name',
    path: '/group/$name',
    getParentRoute: () => experimentalExperimentalProxiesRouteRoute,
});
const experimentalExperimentalProxiesRouteRouteChildren = {
    experimentalExperimentalProxiesIndexRoute: experimentalExperimentalProxiesIndexRoute,
    experimentalExperimentalProxiesGroupNameRoute: experimentalExperimentalProxiesGroupNameRoute,
};
const experimentalExperimentalProxiesRouteRouteWithChildren = experimentalExperimentalProxiesRouteRoute._addFileChildren(experimentalExperimentalProxiesRouteRouteChildren);
const experimentalExperimentalSettingsRouteRouteChildren = {
    experimentalExperimentalSettingsAboutRouteRoute: experimentalExperimentalSettingsAboutRouteRoute,
    experimentalExperimentalSettingsClashCoreRouteRoute: experimentalExperimentalSettingsClashCoreRouteRoute,
    experimentalExperimentalSettingsClashExternalControllRouteRoute: experimentalExperimentalSettingsClashExternalControllRouteRoute,
    experimentalExperimentalSettingsClashFiledRouteRoute: experimentalExperimentalSettingsClashFiledRouteRoute,
    experimentalExperimentalSettingsClashSettingsRouteRoute: experimentalExperimentalSettingsClashSettingsRouteRoute,
    experimentalExperimentalSettingsDebugUtilsRouteRoute: experimentalExperimentalSettingsDebugUtilsRouteRoute,
    experimentalExperimentalSettingsNyanpasuConfigRouteRoute: experimentalExperimentalSettingsNyanpasuConfigRouteRoute,
    experimentalExperimentalSettingsSystemBehaviorRouteRoute: experimentalExperimentalSettingsSystemBehaviorRouteRoute,
    experimentalExperimentalSettingsSystemProxyRouteRoute: experimentalExperimentalSettingsSystemProxyRouteRoute,
    experimentalExperimentalSettingsSystemServiceRouteRoute: experimentalExperimentalSettingsSystemServiceRouteRoute,
    experimentalExperimentalSettingsUserInterfaceRouteRoute: experimentalExperimentalSettingsUserInterfaceRouteRoute,
    experimentalExperimentalSettingsWebUiRouteRoute: experimentalExperimentalSettingsWebUiRouteRoute,
    experimentalExperimentalSettingsIndexRoute: experimentalExperimentalSettingsIndexRoute,
};
const experimentalExperimentalSettingsRouteRouteWithChildren = experimentalExperimentalSettingsRouteRoute._addFileChildren(experimentalExperimentalSettingsRouteRouteChildren);
const experimentalRouteRouteChildren = {
    experimentalExperimentalConnectionsRouteRoute: experimentalExperimentalConnectionsRouteRoute,
    experimentalExperimentalDashboardRouteRoute: experimentalExperimentalDashboardRouteRoute,
    experimentalExperimentalLogsRouteRoute: experimentalExperimentalLogsRouteRoute,
    experimentalExperimentalProfilesRouteRoute: experimentalExperimentalProfilesRouteRoute,
    experimentalExperimentalProvidersRouteRoute: experimentalExperimentalProvidersRouteRoute,
    experimentalExperimentalProxiesRouteRoute: experimentalExperimentalProxiesRouteRouteWithChildren,
    experimentalExperimentalRulesRouteRoute: experimentalExperimentalRulesRouteRoute,
    experimentalExperimentalSettingsRouteRoute: experimentalExperimentalSettingsRouteRouteWithChildren,
};
const experimentalRouteRouteWithChildren = experimentalRouteRoute._addFileChildren(experimentalRouteRouteChildren);
const legacyRouteRouteChildren = {
    legacyBrowserRoute: legacyBrowserRoute,
    legacyConnectionsRoute: legacyConnectionsRoute,
    legacyDashboardRoute: legacyDashboardRoute,
    legacyLogsRoute: legacyLogsRoute,
    legacyProfilesRoute: legacyProfilesRoute,
    legacyProvidersRoute: legacyProvidersRoute,
    legacyProxiesRoute: legacyProxiesRoute,
    legacyRulesRoute: legacyRulesRoute,
    legacySettingsRoute: legacySettingsRoute,
};
const legacyRouteRouteWithChildren = legacyRouteRoute._addFileChildren(legacyRouteRouteChildren);
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    experimentalRouteRoute: experimentalRouteRouteWithChildren,
    legacyRouteRoute: legacyRouteRouteWithChildren,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
