import { locales } from '@/paraglide/runtime';
export declare const languageOptions: {
    en: string;
    ru: string;
    ja: string;
    ko: string;
    'zh-cn': string;
    'zh-tw': string;
    es: string;
    fr: string;
    de: string;
    ar: string;
    id: string;
    el: string;
    sr: string;
    sk: string;
    sl: string;
    lv: string;
    lt: string;
    fa: string;
    bn: string;
    ta: string;
    ml: string;
    kn: string;
    mr: string;
    gu: string;
    pa: string;
    ne: string;
    si: string;
    lo: string;
    km: string;
    my: string;
    ka: string;
    hy: string;
    az: string;
    kk: string;
    mn: string;
    mk: string;
    sq: string;
    eu: string;
    ca: string;
    gl: string;
    is: string;
    ga: string;
    cy: string;
    af: string;
    sw: string;
};
export declare const languageQuirks: {
    [key: string]: {
        drawer: {
            minWidth: number;
            itemClassNames?: string;
        };
    };
};
export type Language = (typeof locales)[number];
export declare const LANGUAGE_STORAGE_KEY = "paraglide-language-cache";
export declare const DEFAULT_LANGUAGE = "en";
export declare const setCachedLanguage: (locale: Language) => void;
export declare const getCachedLanguage: () => "en" | "zh-cn" | "zh-tw" | "ru" | "ja" | "ko" | "es" | "fr" | "de" | "ar" | "id" | "el" | "sr" | "sk" | "sl" | "lv" | "lt" | "fa" | "bn" | "ta" | "ml" | "kn" | "mr" | "gu" | "pa" | "ne" | "si" | "lo" | "km" | "my" | "ka" | "hy" | "az" | "kk" | "mn" | "mk" | "sq" | "eu" | "ca" | "gl" | "is" | "ga" | "cy" | "af" | "sw";
